site_name: "UAI Modal"
nav:
  - "Home": index.md
  - "Deploy": deploy.md
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - contant.tabs.link
    - contant.code.annotation
    - contant.code.copy

plugins:
- search

# - gen-files:
#     scripts:
#     - docs/gen_ref_pages.py 
- literate-nav:
    nav_file: SUMMARY.md

- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [uaimodal]

