site_name: "UAI Diffusers"
nav:
  - "Home": index.md
  - "Classes": classes.md
  - "uaimodal": uaimodal.md
  - "sadTalk": sadtalk.md
  - "hair": hair.md
  - "merger": pipelines_merger.md
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - contant.tabs.link
    - contant.code.annotation
    - contant.code.copy

plugins:
- search

# - gen-files:
#     scripts:
#     - docs/gen_ref_pages.py 
- literate-nav:
    nav_file: SUMMARY.md

- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [uaimodal]

